export const ADMIN_SIGNIN_REQUEST = 'ADMIN_SIGNIN_REQUEST';
export const ADMIN_SIGNIN_SUCCESS = 'ADMIN_SIGNIN_SUCCESS';
export const ADMIN_SIGNIN_FAIL = 'ADMIN_SIGNIN_FAIL';

export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

export const DOCTOR_ADD_REQUEST = 'DOCTOR_ADD_REQUEST';
export const DOCTOR_ADD_SUCCESS = 'DOCTOR_ADD_SUCCESS';
export const DOCTOR_ADD_FAIL = 'DOCTOR_ADD_FAIL';

export const ROOM_ADD_REQUEST = 'ROOM_ADD_REQUEST';
export const ROOM_ADD_SUCCESS = 'ROOM_ADD_SUCCESS';
export const ROOM_ADD_FAIL = 'ROOM_ADD_FAIL';

export const DOCTOR_SIGNIN_REQUEST = 'DOCTOR_SIGNIN_REQUEST';
export const DOCTOR_SIGNIN_SUCCESS = 'DOCTOR_SIGNIN_SUCCESS';
export const DOCTOR_SIGNIN_FAIL = 'DOCTOR_SIGNIN_FAIL';

export const DOCTOR_LOGOUT = 'DOCTOR_LOGOUT';

export const PATIENT_ADD_REQUEST = 'PATIENT_ADD_REQUEST';
export const PATIENT_ADD_SUCCESS = 'PATIENT_ADD_SUCCESS';
export const PATIENT_ADD_FAIL = 'PATIENT_ADD_FAIL';

export const CHECKUP_ADD_REQUEST = 'CHECKUP_ADD_REQUEST';
export const CHECKUP_ADD_SUCCESS = 'CHECKUP_ADD_SUCCESS';
export const CHECKUP_ADD_FAIL = 'CHECKUP_ADD_FAIL';

